sudo: false
language: node_js
node_js: node
cache:
  directories:
  - node_modules
install:
- npm install gitbook-cli broken-link-checker
- node_modules/.bin/gitbook install
- node_modules/.bin/gitbook serve --no-live --no-watch &
# wait for gitboook serve spinup
- sleep 10
script: node_modules/.bin/blc -r http://localhost:4000
